### PR TITLE
Reviews view

### PR DESCRIPTION
**Pull request by Rangatin**
**SUMMARY**:

- Comment button is now correctly disabled, when either the comment is white space or the star rating is 0. I've checked all available outcomes (I think so), so if you find any further bugs, **LET ME KNOW**. I've left the checking also in the controller (for safety measures, if anything goes wrong in the javascript code).

- Removed 'Top' (scroll to top) button, because it overlaid with the 'Report bug' link. The overlay wasn't the reason it was removed - to prevent overlaying, the bottom margin of this 'Top' button was increased, thus resulting in poor design - it appears almost in the middle of the page. Javascript code, related to this button was also removed (**from both the AllVendorsx.cshtml and the Index.cshtml**).

- Changed the design of the vendor card, specifically: its background color has been set to dim gray and the picture of the vendor now looks more like a circle;) and the type is now displayed in capitalized muted text. Apologies, @StauceLukas for changing your design a bit;)
Now, the card looks like this: 
image

Do you like this design? Have any suggestions? Write them in the comments;)
- The request page resubmition is fixed. (A bit outdated)

- Some very minor code refactoring and empty line deletions.

### CODE REVIEW

**Review by HabaHaba05 — APPROVED** [review]
Beautiful card.

**Comment by HabaHaba05** [comment]
Ohh, as I said cards are beautiful, but it's not responsive :( 

image

**Comment by Rangatin** [comment]
> Ohh, as I said cards are beautiful, but it's not responsive :(
> 
> image

Oh, I see. Will fix that.

**Review by Rangatin — COMMENTED** [review]
The cards are now responsive:
image

I tried making images not fixed, but as they are not the same size nor the shape, I left them as it is now.

**Review by HabaHaba05 — APPROVED** [review]

**Pull request merged**
